services:
  patient-service:
    build:
      context: ../hms-patient-service
      dockerfile: Dockerfile
    container_name: hms-patient-service
    ports:
      - "9001:9001"
    networks:
      - hms-network

  doctor-service:
    build:
      context: ../hms-doctor-service
      dockerfile: Dockerfile
    container_name: hms-doctor-service
    ports:
      - "9002:9002"
    environment:
      - PAYMENT_URL=http://payment-service:9006/v1/payments/
      - NOTIFICATION_URL=http://notification-service:9007/v1/notifications/
    depends_on:
      - payment-service
      - notification-service
    networks:
      - hms-network

  notification-service:
    build:
      context: ../hms-notification-service
      dockerfile: Dockerfile
    container_name: hms-notification-service
    ports:
      - "9006:9006"
    networks:
      - hms-network
  
  payment-service:
    build:
      context: ../hms-payment-service
      dockerfile: Dockerfile
    container_name: hms-payment-service
    ports:
      - "9007:9007"
    networks:
      - hms-network

  billing-service:
    build:
      context: ../hms-billing-service
      dockerfile: Dockerfile
    container_name: hms-billing-service
    ports:
      - "9005:9005"
    environment:
      APPOINTMENT_SERVICE_URL: http://appointment-service:9003/v1
    depends_on:
      - patient-service
    networks:
      - hms-network
  
  appointment-service:
    build:
      context: ../hms-appointment-service
      dockerfile: Dockerfile
    container_name: hms-appointment-service
    ports:
      - "9003:9003"
    environment:
      - PATIENT_SERVICE_URL=http://patient-service:9001/v1
      - DOCTOR_SERVICE_URL=http://doctor-service:9002/v1
    depends_on:
      - patient-service
      - doctor-service
    networks:
      - hms-network

  prescription-service:
    build:
      context: ../hms-prescription-service
      dockerfile: Dockerfile
    container_name: hms-prescription-service
    ports:
      - "9004:9004"
    networks:
      - hms-network

  gateway-service:
    build:
      context: ../hms-gateway-service
      dockerfile: Dockerfile
    container_name: hms-gateway-service
    ports:
      - "9000:9000"
    environment:
      PATIENT_SERVICE_URL: http://patient-service:9001/v1
      BILLING_SERVICE_URL: http://billing-service:9005/v1
      APPOINTMENT_SERVICE_URL: http://appointment-service:9003/v1
      PRESCRIPTION_SERVICE_URL: http://prescription-service:9004/v1
    depends_on:
      - patient-service
      - billing-service
      - appointment-service
      - prescription-service
    networks:
      - hms-network

networks:
  hms-network:
    driver: bridge