apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointment-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointment
  template:
    metadata:
      labels:
        app: appointment
    spec:
      containers:
        - name: appointment
          image: hms-integration-compose-appointment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9003